### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by jhiemer** [openservicebrokerapi/osb-checker#18]
Hi,
just running `mocha` for test execution does not work on most machines. People who are not familiar with node should get the hint of running:

If you see a `command not found` message in the terminal, when executing `mocha`, please try to use: `node node_modules/.bin/mocha` in the tests folder.

Does that make sense?

**Comment by Sp0rTB4cK** [comment]
This made my day! I'm running a mac and this was exactly my problem. This should be added to the docs!

**Comment by leonwanghui** [comment]
Hi @jhiemer @Sp0rTB4cK , could you try it again with the containerized deployment? If works, we can close this issue : )

**Comment by leonwanghui** [comment]
I'll close this issue for now, please be free to reopen it if you have any question : )
