### ISSUE TITLE
No schema validation tests for update service instance and create binding

### ISSUE THREAD

**Issue by mattmcneeney** [openservicebrokerapi/osb-checker#27]
There are tests checking service instance create schema validation, but not for update service instance or create binding. Can someone look at adding these?

The existing schema tests should also be optional, as schemas are not a required part of the OSBAPI specification.

**Comment by leonwanghui** [comment]
I'm interested in this project, so I can take a look if nobody else wants : )

**Comment by leonwanghui** [comment]
Already solved by #63
