### ISSUE TITLE
Add ESLint for the project

### ISSUE THREAD

**Issue by zhongyi-zhang** [openservicebrokerapi/osb-checker#56]
ESLint checking should be also added to CI after merging https://github.com/openservicebrokerapi/osb-checker/pull/54.

**Comment by norshtein** [comment]
Will you go to implement this?

**Comment by zhongyi-zhang** [comment]
Yeah, self-assigned.

**Comment by zhongyi-zhang** [comment]
Just initialized the linter. Too many lint issues. To avoid conflicts hard to resolve, I am leaving it here after picking up most of the old PRs.
