### ISSUE TITLE
Incorrect query string in async deprovision test

### ISSUE THREAD

**Issue by stefan-sto** [openservicebrokerapi/osb-checker#57]
It looks like the [query string](https://github.com/openservicebrokerapi/osb-checker/blob/master/2.13/tests/test/test.js#L627) in async deprovsion test is incorrect (two question marks): 
/v2/service_instances/8f020c46-c74e-54d5-f3a6-c8c25f422d6c?plan_id=0f4008b5-XXXX-XXXX-XXXX-dace631cd648&service_id=acb56d7c-XXXX-XXXX-XXXX-feb140a59a66?accepts_incomplete=false

I think that the line should be changed to use '&' instead of '?':
`.delete(handler + '&accepts_incomplete=false')`

Also it seems like the code that invokes [`.send()`](https://github.com/openservicebrokerapi/osb-checker/blob/master/2.13/tests/test/test.js#L630) is not needed as the service_id and the plan_id are part of the query string.

**Comment by leonwanghui** [comment]
@stefan-sto Sure, my glad : )
